name: StoryPlay Develop Release!

on:
  pull_request:
    branches:
      - develop

jobs:
  main:
    name: Echo Develop test
    runs-on: ubuntu-latest
    steps:
      - name: test echo
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        run: echo Hello GitHub Action!
